"""add_google_calendar_fields

Revision ID: 09867aa12d12
Revises: c70123f643d7
Create Date: 2026-04-26 16:44:13.564020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09867aa12d12'
down_revision: Union[str, Sequence[str], None] = 'c70123f643d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profiles', sa.Column('provider', sa.String(), nullable=False))
    op.add_column('Profiles', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('Todos', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Todos', 'google_event_id')
    op.drop_column('Profiles', 'google_refresh_token')
    op.drop_column('Profiles', 'provider')
    # ### end Alembic commands ###
