"""initial migration

Revision ID: 705bbe66663c
Revises: 
Create Date: 2026-04-26 16:16:15.243266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705bbe66663c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Profiles_email'), 'Profiles', ['email'], unique=True)
    op.create_index(op.f('ix_Profiles_id'), 'Profiles', ['id'], unique=False)
    op.create_table('Todos',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Todos_id'), 'Todos', ['id'], unique=False)
    op.create_index(op.f('ix_Todos_user_id'), 'Todos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Todos_user_id'), table_name='Todos')
    op.drop_index(op.f('ix_Todos_id'), table_name='Todos')
    op.drop_table('Todos')
    op.drop_index(op.f('ix_Profiles_id'), table_name='Profiles')
    op.drop_index(op.f('ix_Profiles_email'), table_name='Profiles')
    op.drop_table('Profiles')
    # ### end Alembic commands ###
